### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by jplatte** [citreae535/sparse-crates#2]
Hey, could you maybe publish this extension to https://open-vsx.org/ in addition to Microsoft's VSCode marketplace?

Thanks for your efforts!

**Comment by citreae535** [comment]
Thanks for your suggestion! Just published at https://open-vsx.org/extension/citreae535/sparse-crates

**Comment by Throne3d** [comment]
Would it be possible to link both the Microsoft marketplace one and Open VSX one in the README? =D I wasn't able to see them there. It was pretty easy to find when searching in the extensions menu for me, but I find it's usually standard to have a link to it in the README too, which can help make sure it's definitely the version that corresponds to this repo

(Thanks for the tool! I've been struggling with an outdated indexes issue with the original `crates`, which this is already helping with)

**Comment by jplatte** [comment]
Just installed, works. Thanks!
