### ISSUE TITLE
Is this crate open to contributors?

### ISSUE THREAD

**Issue by fawadasaurus** [citreae535/sparse-crates#3]
Hello.

I was wondering if this crate is open to contributors?

I wanted to add some functionality to this crate to use the `~/.cargo/config.toml` and `credentials.toml` file automatically so it can authenticate to private crate repositories.

Please let me know if you are open to this contribution.

Thanks

**Comment by citreae535** [comment]
Hi,

It's been a while since I last worked on this project, so it'll take me some time to bring the project up to date and review your pull request. But, thanks for your interest in this extension! All contributions are welcome.

Regards
